# Generated by Django 4.2.19 on 2025-02-28 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0003_sensormeasurement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensormeasurement",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="sensormeasurement",
            old_name="name",
            new_name="sensor_name",
        ),
        migrations.AddField(
            model_name="hydroponicsystem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hydroponicsystem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hydroponicsystem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
